# ✅ User Profile Settings
user_profile:
  medium_username: "codingoni"  # Replace with your Medium username
  target_audience: "Non Technical People Looking For Tech Thought Leadership"  # Replace with your target audience
  professional_summary: "I'm a Software Engineer with a passion for creating innovative solutions and sharing my knowledge with the world. I'm always looking for new ways to improve my skills and help others do the same."  # Replace with your professional summary
  resume_url: "https://www.linkedin.com/in/your-linkedin-url"  # Replace with your LinkedIn URL
  llm:
    OpenAIAssistant:
        enabled: true  # Set to true to use this provider
        temperature: 0.7  # Adjusts randomness of responses (0 = strict, 1 = creative)
        max_tokens: 500  # Token limit for responses
       
    OpenAI:
      enabled: true  # Set to true to use this provider
      model: "gpt-4o-mini"
      temperature: 0.7  # Adjusts randomness of responses (0 = strict, 1 = creative)
      max_tokens: 500  # Token limit for responses
      available_models:
        - "gpt-4o"
        - "gpt-4o-mini"
        - "gpt-3.5-turbo"
        
    DeepSeek:
      enabled: false
      model: "deepseek-chat"
      temperature: 0.7
      max_tokens: 500
      available_models:
        - "deepseek-chat"
        - "deepseek-coder"
        - "deepseek-text"

    Anthropic:
      enabled: false
      model: "claude-3-sonnet"
      temperature: 0.7
      max_tokens: 500
      available_models:
        - "claude-3-opus"
        - "claude-3-sonnet"
        - "claude-3-haiku"

    Cohere:
      enabled: false
      model: "command-r"
      temperature: 0.7
      max_tokens: 500
      available_models:
        - "command-r-plus"
        - "command-r"

    Ollama:
      enabled: false
      model: "llama3:8b"
      temperature: 0.7
      max_tokens: 500
      available_models:
        - "llama3:8b"
        - "llama3:70b"
        - "mistral:7b"

    HuggingFace:
      enabled: false
      model: "meta-llama/Meta-Llama-3-8B"
      temperature: 0.7
      max_tokens: 500
      available_models:
        - "meta-llama/Meta-Llama-3-8B"
        - "mistralai/Mistral-7B-Instruct-v0.1"
        - "tiiuae/falcon-7b-instruct"

    Custom:
      enabled: false
      model: "your-custom-model"
      temperature: 0.7
      max_tokens: 500
      url: "https://your-custom-api.com/v1/completions"
      headers:
        Authorization: "Bearer your_api_key"
        Content-Type: "application/json"
  # ✅ Creative Preferences (Visuals & Storytelling)


# ✅ Social Media Platforms
social_media_to_post_to:
  linkedin:
    enabled: true
    post_format: "Text"  # Options: Markdown, HTML, or None
    maximum_characters: 260  # Maximum number of characters allowed

# ✅ OpenAI Configuration & Content Generation
openai:
  custom_system_instructions: None  # Optional system-level AI instructions
  custom_user_instructions: None  # Optional user-level AI guidance

  creative:
    generate_image:
      enabled: true
      description: "If true, generates an AI image tailored to the post."
      prompt: "Create a high-quality AI-generated image relevant to the blog content."
      
    fetch_gif:
      enabled: false
      description: "If true, ai suggests tags from giphy then pick the giph with the most relevant title"
      prompt: "EX: Focus on gifs that will be most impactful relevant to the blog"

# (Coming SOON)
    post_video:
      enabled: false
      description: "If true, includes a video in the LinkedIn post to boost engagement."
      prompt: "Generate a video that highlights the key points of the blog post."

  viral_posting:
    include_viral_formatting:
      enabled: true
      description: "Ensures AI-generated posts follow viral structures."
      
    attention_grabbing_intro:
      enabled: true
      description: "First sentence must hook the reader to capture attention."
      
    emotional_storytelling:
      enabled: true
      description: "Includes personal/emotional elements to increase relatability."
      
    extreme_statements:
      enabled: false
      description: "Uses bold statements to spark engagement/debate (if enabled)."
      
    relatable_experiences:
      enabled: true
      description: "Ensures the post connects with the audience's daily struggles."
      
    actionable_takeaways:
      enabled: true
      description: "Posts must offer practical insights or solutions for readers."
      
    data-backed_claims:
      enabled: true
      description: "Uses real data & examples to establish credibility and trust."

  viral_posts_i_liked:
    - text: "I was rejected by 30 companies before landing my dream job. Now, I mentor others to never give up. 💪 #Resilience #CareerGrowth"
      engagement: 50K+ likes, 10K+ shares
      creative: "[GIF] of a person overcoming obstacles"
      creative_asset: "https://example.com/obstacle-overcome.gif"
      reason: "Personal story of failure & success, highly relatable"
    
    - text: "AI won’t replace you. But a person using AI will. Are you adapting? 🚀 #ArtificialIntelligence #FutureOfWork"
      engagement: 100K+ likes, 20K+ shares
      creative: "[IMG] Person Using AI"
      creative_asset: "https://example.com/obstacle-overcome.gif"

      reason: "Bold statement, sparks debate & FOMO"

    - text: "Quit my 6-figure job to chase my passion. Scariest but best decision ever. If you're stuck, this is your sign. 🔥 #CareerChange"
      engagement: 75K+ likes, 15K+ shares
      creative: "UGC Candid Video"
      reason: "Emotional + inspirational, triggers engagement"
      creative_asset: "https://example.com/obstacle-overcome.gif"

# ✅ Hashtags for Engagement
hashtags:
  default_tags:
    - "#AI"
    - "#MachineLearning"
    - "#DataScience"
    - "#Automation"
    - "#Technology"
  custom_tags: []  # Users can add their own custom hashtags here
