name: RSS to LinkedIn

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  check_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Restore Latest Post Cache
        id: cache_latest
        uses: actions/cache@v3
        with:
          path: latest_post.txt
          key: latest-post

     - name: Fetch RSS Feed
        id: fetch_rss
        run: |
          FEED_URL="https://medium.com/feed/${{ secrets.MEDIUM_USERNAME }}"
          LATEST_ENTRY=$(curl -s "$FEED_URL" | xmllint --xpath '//item[1]/link/text()' - 2>/dev/null || echo "")

          # If latest_post.txt does not exist, create it
          if [ ! -f latest_post.txt ]; then
            echo "No previous post found. Storing current post."
            echo "$LATEST_ENTRY" > latest_post.txt
            echo "new_post=false" >> $GITHUB_ENV
            exit 0
          fi

          PREVIOUS_ENTRY=$(cat latest_post.txt)

          if [ "$LATEST_ENTRY" != "$PREVIOUS_ENTRY" ] && [ -n "$LATEST_ENTRY" ]; then
            echo "new_post=true" >> $GITHUB_ENV
            echo "$LATEST_ENTRY" > latest_post.txt
          else
            echo "new_post=false" >> $GITHUB_ENV
          fi
      - name: Check for new post
        id: check_new_post
        run: |
          if [ ! -f latest_post.txt ] || ! grep -q "$LATEST_ENTRY" latest_post.txt; then
            echo "new_post=true" >> $GITHUB_ENV
            echo "$LATEST_ENTRY" > latest_post.txt
          else
            echo "new_post=false" >> $GITHUB_ENV
          fi

      - name: Process blog post
        if: env.new_post == 'true'
        id: process_blog
        run: |
          RESPONSE=$(curl -X POST "https://your-api.com/process" -H "Content-Type: application/json" \
            -d '{"url": "'"$LATEST_ENTRY"'"}')
          echo "processed_content=$RESPONSE" >> $GITHUB_ENV

      - name: Post to LinkedIn
        if: env.new_post == 'true'
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: |
          curl -X POST "https://api.linkedin.com/v2/ugcPosts" \
            -H "Authorization: Bearer $LINKEDIN_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "author": "urn:li:person:yourLinkedInID",
              "lifecycleState": "PUBLISHED",
              "specificContent": {
                "com.linkedin.ugc.ShareContent": {
                  "shareCommentary": {
                    "text": "'"$processed_content"'"
                  },
                  "shareMediaCategory": "ARTICLE",
                  "media": [{
                    "status": "READY",
                    "originalUrl": "'"$LATEST_ENTRY"'"
                  }]
                }
              },
              "visibility": {
                "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
              }
            }'
