name: RSS to LinkedIn

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
      GIPHY_ASSET_TOKEN: ${{ secrets.GIPHY_ASSET_TOKEN }}
      MEDIUM_USERNAME: ${{ secrets.MEDIUM_USERNAME }}
      TEST_MODE: true

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install Pipenv
        run: pip install pipenv

      - name: 📦 Install Dependencies with Pipenv
        run: pipenv install --deploy --ignore-pipfile

      - name: ♻️ Ensure Cache Path Exists
        run: mkdir -p _temp && touch _temp/blog_cache.json

      - name: ♻️ Restore Blog Cache
        uses: actions/cache@v3
        with:
          path: _temp/blog_cache.json
          key: blog-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            blog-cache-

      - name: 🚀 Run Main App Script
        run: pipenv run app

      - name: 💾 Save Blog Cache
        if: always()
        uses: actions/cache@v3
        with:
          path: _temp/blog_cache.json
          key: blog-cache-${{ runner.os }}-${{ github.run_id }}